#!/bin/bash
#
# lib/mlnx_dnsmasq
# Functions to control the configuration and operation of the mlnx_dnsmasq driver
# <do not include this template file in ``stack.sh``!>

# Dependencies:
#
# - ``functions`` file
# - ``SERVICE_{TENANT_NAME|PASSWORD}`` must be defined
# - <list other global vars that are assumed to be defined>

# ``stack.sh`` calls the entry points in this order:
#
# - install_mlnx_dnsmasq
# - configure_mlnx_dnsmasq


# Save trace setting
MY_XTRACE=$(set +o | grep xtrace)
set +o xtrace


NEUTRON_DCHP_CONF=/etc/neutron/dhcp_agent.ini

function install_mlnx_dnsmasq {
    :
}

function configure_mlnx_dnsmasq {
    iniset /$NEUTRON_DCHP_CONF DEFAULT dhcp_broadcast_reply True
    iniset /$NEUTRON_DCHP_CONF DEFAULT dhcp_driver networking_mlnx.dhcp.mlnx_dhcp.MlnxDnsmasq
}

function init_mlnx_dnsmasq {
    :
}

function start_mlnx_dnsmasq {
   :
}

function stop_mlnx_dnsmasq {
   :
}

function check_mlnx_dnsmasq {
    :
}

function cleanup_mlnx_dnsmasq {
    :
}

# Restore trace
$MY_XTRACE
